review-changes:
	git log --reverse $( git tag | tail -1 )..HEAD | vim -o - -c 'new Changes' 
README.md:
	pod2markdown lib/WWW/FatPacked.pod > README.md
skaufman-release: preflight README.md
	$(MAKE) disttest
	rm -rf $(DISTVNAME)
	$(MAKE) $(DISTVNAME).tar$(SUFFIX)
	cp $(DISTVNAME).tar$(SUFFIX) /tmp/
	git commit -a -m "Release commit for $(VERSION)"
	git tag v$(VERSION) -m "release v$(VERSION)"
	git push --tags
	git push
